server:
  port: 9091

spring:
  application:
    name: SECURITY-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    path: /security-service/v3/api-docs
  swagger-ui:
    config-url: /security-service/v3/api-docs
