server:
  port: 8080

spring:
  application:
      name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: User-Microservice
          uri: lb://USER-MICROSERVICE
          predicates:
            - Path=/user/**,/user-service/v3/api-docs
        - id:
          uri: lb://SECURITY-SERVICE
          predicates:
              - Path=/auth/**,/security-service/v3/api-docs
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
    eureka:
      client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
          defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: Api-Gateway-service
      - url: /user-service/v3/api-docs
        name: user-service
      - url: /security-service/v3/api-docs
        name: security-service